name: SimpleFileStoreForTests
comment: simple file store only for testing purposes
author: Mikel Egana Aranguren
pluginClassName: es.eurohelp.lod.aldapa.impl.storage.LocalFileStore
storeDirectory: LocalFileStore
metadataFile: LocalFileStore/Metadata.yml