name: LinkDiscovererForTests
comment: Links discoverer for testing purposes
author: Mishel Uchuari

pluginClassName: es.eurohelp.lod.aldapa.impl.modification.SILKLinkDiscovery
silkConfigurationFile: data/linkdiscoverer/silk-configuration.xml
silkResultsPath: data/linkDiscoverer/accepted-links.nt