# THIS CONFIGURATION
name: SimpleFileStoreForTests
comment: simple file store only for testing purposes
author: Mikel Egana Aranguren

# Plugin with actual code for accesing the Triple Store
pluginClassName: es.eurohelp.lod.aldapa.impl.storage.LocalFileStore

# Directory to store CSV files
storeDirectory: data/LocalFileStore/

# Metadata to keep track of the names and URLs of the stored files
metadataFile: data/LocalFileStore/Metadata.yml