name: SHACLValidatorForTests
comment: SHACL validator for testing purposes
author: Mikel Egana Aranguren

pluginClassName: es.eurohelp.lod.aldapa.impl.modification.SHACLValidator
dataGraph: http://euskadi.eus/graph/estaciones
shapeGraph: data/shacl/estaciones-shape.ttl
reportFile: data/shacl/estaciones.ttl