PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcat:<http://www.w3.org/ns/dcat#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX schema:<http://schema.org/>

SELECT ?catalog 
WHERE {
	PROJECT_URI rdf:type foaf:Project .	
	?catalog rdf:type dcat:Catalog .
	?catalog dcat:dataset ?dataset .
	?catalog schema:isPartOf PROJECT_URI .
}