PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcat:<http://www.w3.org/ns/dcat#>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX schema:<http://schema.org/>
PREFIX void:<http://rdfs.org/ns/void#>

SELECT ?dataset 
WHERE {
		CATALOG_URI rdf:type dcat:Catalog .
		CATALOG_URI dcat:dataset ?dataset .
		?dataset rdf:type dcat:Distribution . 
		?dataset rdf:type void:Dataset . 
		?dataset rdf:type schema:Distribution .
}