PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX void: <http://rdfs.org/ns/void#>

ASK 
WHERE {
	DATASET_URI rdf:type dcat:Distribution, void:Dataset, schema:Distribution .
}



